#!/bin/sh

set -e
set -x
if [ -f Makefile ]; then
  make distclean
fi
rm -rf *~ *.cache *.m4 config.guess config.log config.status config.sub depcomp ltmain.sh

if test ! -z "$1"; then
    cp configure.ac configure.ac.orig
    sed 's/^define(\[PACKAGE_SUFFIX\],\s*\[\([-~]*[0-9a-zA-Z]*\)\])$/define(\[PACKAGE_SUFFIX\], \['$1'\])/g' configure.ac.orig > configure.ac
fi

if test ! -z "$2"; then
    cp configure.ac configure.ac.orig
    sed 's/^define(\[PACKAGE_VERSION_REVISION\],\s*\[\([-~]*[0-9a-zA-Z]*\)\])$/define(\[PACKAGE_VERSION_REVISION\], \['$2'\])/g' configure.ac.orig > configure.ac
fi

if [ ! -z "$3" ]; then
    echo "Third parameter $3"
    if [ "$3" != "master" ]; then
        cp configure.ac configure.ac.orig
        sed 's/^define(\[PACKAGE_BRANCH\],\s*\[\([-~]*[0-9a-zA-Z]*\)\])$/define(\[PACKAGE_BRANCH\], \['-$3'\])/g' configure.ac.orig > configure.ac
    fi
fi

autoreconf --verbose --install --force
